const TransactionActionTypes = {
  ADD_TRANSACTION_START: 'ADD_TRANSACTION_START',
  ADD_TRANSACTION_SUCCESS: 'ADD_TRANSACTION_SUCCESS',
  ADD_TRANSACTION_FAILURE: 'ADD_TRANSACTION_FAILURE',
  FETCH_TRANSACTIIONS_START: 'FETCH_TRANSACTIIONS_START',
  FETCH_TRANSACTIIONS_SUCCESS: 'FETCH_TRANSACTIIONS_SUCCESS',
  FETCH_TRANSACTIIONS_FAILURE: 'FETCH_TRANSACTIIONS_FAILURE',
};

export default TransactionActionTypes;
