const TransactionActionTypes = {
  ADD_TRANSACTION_START: 'ADD_TRANSACTION_START',
  ADD_TRANSACTION_SUCCESS: 'ADD_TRANSACTION_SUCCESS',
  ADD_TRANSACTION_FAILURE: 'ADD_TRANSACTION_FAILURE',
  FETCH_TRANSACTIIONS_START: 'FETCH_TRANSACTIIONS_START',
  FETCH_TRANSACTIIONS_SUCCESS: 'FETCH_TRANSACTIIONS_SUCCESS',
  FETCH_TRANSACTIIONS_FAILURE: 'FETCH_TRANSACTIIONS_FAILURE',
  DELETE_TRANSACTION_START: 'DELETE_TRANSACTION_START',
  DELETE_TRANSACTION_SUCCESS: 'DELETE_TRANSACTION_SUCCESS',
  DELETE_TRANSACTION_FAILURE: 'DELETE_TRANSACTION_FAILURE',
  CLEAR_TRANSACTIONS: 'CLEAR_TRANSACTIONS',
};

export default TransactionActionTypes;
